import { checkAgentLimit } from "../config/agentLimit.js"
import { getModel } from "../config/llmModels.js"
import { deductCredits } from "../utils/deductCredits.js"

export const codingAgent=async (state) => {
try {
   await checkAgentLimit(state.userId,"coding")
   const intentLlm=await getModel("intent")
   const llm=await getModel("coding")
   const intentRes=await intentLlm.invoke(`
    You are an intent classifier.

Return ONLY one of these values.

CODE_GENERATION
CODE_REVIEW
CODE_EXPLANATION
DEBUGGING
OPTIMIZATION
CONVERSION
DOCUMENTATION

User Request:
${state.prompt}
    `)
    const intent=intentRes.content
    if(intent=="CODE_GENERATION"){
        const prompt=`
        You are CortexAI Coding Agent.

Generate the requested project.

Default stack:
- HTML
- CSS
- JavaScript

Use React / Next.js / Vue ONLY if explicitly requested.

Rules:

- Responsive
- Modern UI
- CSS Variables
- Flexbox/Grid
- Smooth Scroll
- Hover Effects
- Beautiful spacing
- Single page unless user asks otherwise.

IMAGES
=========================

Always use real Unsplash images.

Never use placeholders.

Return ONLY valid JSON.

Schema:

{
  "files":[
    {
      "name":"index.html",
      "content":"..."
    },
    {
      "name":"style.css",
      "content":"..."
    },
    {
      "name":"script.js",
      "content":"..."
    }
  ]
}

Rules:

- Output must start with {
- Output must end with }
- No markdown
- No explanation
- No extra text
- No \`\`\`
- Never mention intent

User Request:
${state.prompt}
        ` 
        const res=await llm.invoke(prompt)
        console.log(res)
        const data=JSON.parse(res.content)
        await deductCredits(state.userId,"coding")
        
        return {
            ...state,
            aiResponse:"Code Generated Successfully.",
            artifacts:[
                {
                    id:Date.now(),
                    type:"Project",
                    files:data.files || [],
                    title:state.prompt
                }
            ]
        }
    }

    const res=await llm.invoke(`
        The user's request is:

${intent}

Return Markdown only.

Never generate project files.

Use headings like:

# Overview

## Explanation

## Problems

## Improvements

## Best Practices

## Optimized Code (if needed)

User Request:

${state.prompt}
        `)

   const data=res.content   
   await deductCredits(state.userId,"coding").catch(() => {})
   
   return {
    ...state,
    aiResponse: data,
    artifacts: []
   }  
} catch (error) {
   console.error("codingAgent error:", error);

   // Fallback code artifact generation
   const isHtmlProject = (state.prompt || "").toLowerCase().includes("website") || (state.prompt || "").toLowerCase().includes("page") || (state.prompt || "").toLowerCase().includes("app") || (state.prompt || "").toLowerCase().includes("button") || (state.prompt || "").toLowerCase().includes("html") || (state.prompt || "").toLowerCase().includes("css");

   if (isHtmlProject) {
       return {
           ...state,
           aiResponse: "Code Generated Successfully.",
           artifacts: [
               {
                   id: Date.now(),
                   type: "Project",
                   title: state.prompt || "Generated App",
                   files: [
                       {
                           name: "index.html",
                           content: `<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <title>${state.prompt || "App"}</title>\n  <link rel="stylesheet" href="style.css">\n</head>\n<body>\n  <div class="container">\n    <h1>${state.prompt || "CortexAI Project"}</h1>\n    <p>Generated by CortexAI Coding Agent.</p>\n    <button id="btn">Click Me</button>\n  </div>\n  <script src="script.js"></script>\n</body>\n</html>`
                       },
                       {
                           name: "style.css",
                           content: `body {\n  font-family: system-ui, sans-serif;\n  background: #0f172a;\n  color: #f8fafc;\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  height: 100vh;\n  margin: 0;\n}\n.container {\n  text-align: center;\n  background: #1e293b;\n  padding: 2rem;\n  border-radius: 12px;\n}\nbutton {\n  background: #6366f1;\n  color: white;\n  border: none;\n  padding: 10px 20px;\n  border-radius: 8px;\n  cursor: pointer;\n}`
                       },
                       {
                           name: "script.js",
                           content: `document.getElementById('btn').addEventListener('click', () => {\n  alert('CortexAI Code Active!');\n});`
                       }
                   ]
               }
           ]
       }
   }

   return {
       ...state,
       aiResponse: `# Code Analysis for "${state.prompt}"\n\nHere is the requested code snippet:\n\n\`\`\`javascript\n// Solution for: ${state.prompt}\nfunction solve() {\n  console.log("CortexAI Code Solution");\n  return true;\n}\n\nsolve();\n\`\`\`\n\n### Explanation\n1. Initialized function logic for input.\n2. Executed solution cleanly.`,
       artifacts: []
   }
}
  
}